spring:
  cloud:
    gateway:
      routes:
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=2

        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vets/**
          filters:
            - StripPrefix=2

        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visits/**
          filters:
            - StripPrefix=2


server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
